# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - '386'
    ldflags:
      - -s -w

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  use: github-native
  sort: asc
brews:
  -
    # Repository to push the tap to.
    tap:
      owner: fengjx
      name: homebrew-lc

    # Your app's homepage.
    homepage: 'https://github.com/fengjx/lc'

    # Your app's description.
    # Default is empty.
    description: '是一个类似 Django 命令行工具，旨在快速生成 lca(https://github.com/fengjx/lca) 模板代码'