ds: # 数据库连接
  type: mysql
  dsn: root:1234@tcp(192.168.1.200:3306)/gogo
target:
  custom:  # 自定义配置
    tag-name: json # 生成 entity tag
    out-dir: ./out # 代码输出目录
    var: # 自定义变量（key-value）
      foo: bar
  tables: # 数据库表  table_name: {} 自定义表配置
    user: {module: sys}
    blog: {module: core}
