ds: # 数据库连接
  type: mysql
  dsn: root:1234@tcp(localhost:3306)/lca?charset=utf8mb4
target:
  custom:                                     # 自定义配置
    tag-name: json                            # 生成 entity tag
    # template-dir: ./commands/gen/template   # 自动以模板根目录
    out-dir: ./out/migrate                    # 代码输出目录
    use-admin: true                           # 是否生成管理后台页面
    gomod: github.com/fengjx/demo             # go.mod 中的 module
    var:                                      # 自定义变量（key-value）
      foo: bar
  tables:                                     # 数据库表  table_name: {} 自定义表配置
    sys_user:
      module: sys
      simple-name: user
    sys_config:
      module: sys
      simple-name: config
    sys_dict:
      module: sys
      simple-name: dict
    sys_menu:
      module: sys
      simple-name: menu
