name: release template

on:
  push:
    tags:
      - 'template-*'

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Unshallow repo
        run: git fetch --prune --unshallow
      - name: build template zip
        run: |
             mkdir -p .dist/template
             cp -r commands/start/template .dist/template/start
             cp -r commands/migrate/template .dist/template/migrate
             cd .dist
             zip -r template.zip template -x ".git/*" ".github/*"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .dist/template.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
